version: 2.0.{build}

branches:
  only:
    - master

skip_tags: true
skip_branch_with_pr: true

environment:
  choco_key:
    secure: thGHMWkNaQFVFcE2DCi3XHW2mgPIWuUVNITbLlzyL1JEGXbdv0kFfOJOLAJbMHLS

# image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

install:
  - choco pack
  - 'choco push --api-key {choco_key}'

artifacts:
  - path: '**\*.nupkg'